### PR TITLE
Fixed a bug which crashes wallet during seed generation on new wallet creation

### PR DESCRIPTION
**Pull request by harwee**

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
ill test this tonight, i haven't had any seed creation issues, but it could be different in the binary

**Comment by harwee** [comment]
Maybe it's due to windows versions pf libraries, they are not too reliable on windows.

**Comment by ReservedUsername** [comment]
electrum-xvg wallet.
Operation: File: New/Restore, New wallet, leave "wallet_1" by default. 
Electrum Install Wizard options: 1. Create new wallet and Standard wallet, Enter.
Attached file of the error. 
Wallet is not working

electrum

**Comment by harwee** [comment]
Looks like the issue is due to incorrect seed generation, this pull request should fix that.

**Comment by harwee** [comment]
Closing pull request as I merged the code with core code on development branch.

**Comment by ReservedUsername** [comment]
good job. thanks

**Comment by kmu36323** [comment]
the same problem tell me what to do? how it can be done Closing a Pull-request, as I merged the fix with the main code on the development branch. 
Аnd another on the PC writes that I'm offline internet connected

**Comment by kmu36323** [comment]
image

**Comment by harwee** [comment]
@kmu36323 I cannot read the errors, the resolution is too small can  you upload a better quality picture or type the error?

**Comment by kmu36323** [comment]
image

**Comment by harwee** [comment]
What version of client are you using?

**Comment by kmu36323** [comment]
Hi, 2.4.1.0

2017-11-11 8:18 GMT+03:00 Sri Harsha Gangisetty <notifications@github.com>:

**Comment by harwee** [comment]
That occurs when creating a new wallet from file menu right?
Or can you tell me what you were doing when that occurred.

**Comment by kmu36323** [comment]
this happens when I try to go into the purse I click on the icon to open the wallet

**Pull request closed without merging**
