### PR TITLE
x

### PR DESCRIPTION
**Pull request by ch4ot1c**

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
lol

**Comment by ch4ot1c** [comment]
Pleased to meet you

**Comment by justinvforvendetta** [comment]
good luck with zclassic. thats the one where you guys removed the huge mining reward that went to teh devs right?

**Comment by ch4ot1c** [comment]
Correct! I like the chain alot. We're getting some nicer wallets set up right now, and preparing for the upcoming BTCP fork.

~ Exciting times ~

**Comment by justinvforvendetta** [comment]
@ch4ot1c good for you guys man. i thought the 20% mining reward to devs was pretty shady. glad to see you took matters into your own hands over there. stay well.

**Pull request closed without merging**
